Vidly/Vidly/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
	public class Customer
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}
}

Vidly/Vidly/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
	public class Movie
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}
}

Vidly/Vidly/ViewModels/RandomMovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly.Models;

namespace Vidly.ViewModels
{
	public class RandomMovieViewModel
	{
		public Movie Movie { get; set; }

		public List<Customer> Customers { get; set; }
	}
}

Vidly/Vidly/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
		{
			var customers = GetCustomers();

            return View(customers);
        }

		public ActionResult Edit(int? id)
		{
			if (!id.HasValue) return HttpNotFound();

			var customer = GetCustomers().Where(c=>c.Id==id).FirstOrDefault();
			return View(customer);
		}

		private IEnumerable<Customer> GetCustomers()
		{
			return new List<Customer>() {
				new Customer { Name = "Customer 1", Id = 1},
				new Customer { Name = "Customer 2", Id = 2}
			};
		}
    }
}

Vidly/Vidly/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidly.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

Vidly/Vidly/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movies
        public ActionResult Index()
        {
			var movies = GetMovies();
			return View(movies);
        }

		// GET: Movies/Random
		public ActionResult Random()
		{
			var movie = new Movie() { Name = "Harry Potter!" };

			var customers = new List<Customer>() {
				new Customer { Name = "Customer 1" },
				new Customer { Name = "Customer 2" }
			};

			var viewModel = new RandomMovieViewModel() { Customers = customers, Movie = movie };
		    return View(viewModel);
			//return Content("text");
			//return HttpNotFound();
			//return new EmptyResult(); // prazna stranica
			//return RedirectToAction("Index", "Home", new { page = 1, sortBy = "name" });
		}

		public ActionResult Edit(int id)
		{
			return View();
			// Content("id=" + id);
		}

		[Route("movie/released/{year:regex(\\d{4})}/{month:regex(\\d{2})}")]
		public ActionResult ByReleaseDate(int year, int month)
		{
			return Content(String.Format("{0}/{1}", year, month));
		}

		private IEnumerable<Movie> GetMovies()
		{
			return new List<Movie>() {
				new Movie {Name = "Harry Potter" },
				new Movie { Name = "Shrek"}
			};
		}
	}
}

Vidly/Vidly/Views/Customer/Edit.cshtml
@model Vidly.Models.Customer
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@Model.Name;

Vidly/Vidly/Views/Customer/Index.cshtml
@model  IEnumerable<Vidly.Models.Customer>
	@{
		ViewBag.Title = "Customers";
		Layout = "~/Views/Shared/_Layout.cshtml";
	}

	<h2>
		Customers
	</h2>
@if (!Model.Any())
{
	<p>We don't have any customers yet!</p>
}
else {
	<table class="table table-bordered table-hover">
		<thead>
			<tr>
				<th scope="col">Customer</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var customer in @Model)
			{
			<tr>
				<td>
					@Html.ActionLink(customer.Name, "Edit", "Customer", new { id = customer.Id }, null)
				</td>
			</tr>
			}
		</tbody>
	</table>
}

	

Vidly/Vidly/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Vidly/Vidly/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vidly/Vidly/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Vidly";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Vidly/Vidly/Views/Movie/Edit.cshtml
@Model  Vidly.Models.Movie
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

Vidly/Vidly/Views/Movie/Index.cshtml
@model  IEnumerable<Vidly.Models.Movie>
@{
    ViewBag.Title = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>

@foreach (var movie in Model)
{
	<p>@movie.Name;</p>
}

Vidly/Vidly/Views/Movie/Random.cshtml
@model Vidly.ViewModels.RandomMovieViewModel
@{
	ViewBag.Title = "Movies";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ 
	var className = Model.Customers.Count > 0 ? "popular" : "";
}
<h2 class="@className">@ViewBag.Title</h2>

@Model.Movie.Name;

@foreach (var customer in Model.Customers)
{
	<li>customer.Name</li>
}

Vidly/Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Customers", "Index", "Customer")</li>
					<li>@Html.ActionLink("Movies", "Index", "Movie")</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>